use serde::{Serialize, Deserialize};

#[repr(u8)]
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Program {
    // PIANO
    AcousticGrand = 0,
    BrightAcoustic = 1,
    ElectricGrand = 2,
    HonkyTonk = 3,
    ElectricPiano1 = 4,
    ElectricPiano2 = 5,
    Harpsichord = 6,
    Clavinet = 7,
    // CHROMATIC PERCUSSION
    Celesta = 8,
    Glockenspiel = 9,
    MusicBox = 10,
    Vibraphone = 11,
    Marimba = 12,
    Xylophone = 13,
    TubularBells = 14,
    Dulcimer = 15,
    // ORGAN
    DrawbarOrgan = 16,
    PercussiveOrgan = 17,
    RockOrgan = 18,
    ChurchOrgan = 19,
    ReedOrgan = 20,
    Accordion = 21,
    Harmonica = 22,
    TangoAccordion = 23,
    // GUITAR
    NylonStringGuitar = 24,
    SteelStringGuitar = 25,
    ElectricJazzGuitar = 26,
    ElectricCleanGuitar = 27,
    ElectricMutedGuitar = 28,
    OverdrivenGuitar = 29,
    DistortionGuitar = 30,
    GuitarHarmonics = 31,
    // BASS
    AcousticBass = 32,
    FingerElectricBass = 33,
    PickElectricBass = 34,
    FretlessBass = 35,
    SlapBass1 = 36,
    SlapBass2 = 37,
    SynthBass1 = 38,
    SynthBass2 = 39,
    // SOLO STRINGS
    Violin = 40,
    Viola = 41,
    Cello = 42,
    Contrabass = 43,
    TremoloStrings = 44,
    PizzicatoStrings = 45,
    OrchestralHarp = 46,
    Timpani = 47,
    // ENSEMBLE
    StringEnsemble1 = 48,
    StringEnsemble2 = 49,
    SynthStrings1 = 50,
    SynthStrings2 = 51,
    ChoirAahs = 52,
    VoiceOohs = 53,
    SynthVoice = 54,
    OrchestraHit = 55,
    // BRASS
    Trumpet = 56,
    Trombone = 57,
    Tuba = 58,
    MutedTrumpet = 59,
    FrenchHorn = 60,
    BrassSection = 61,
    SynthBrass1 = 62,
    SynthBrass2 = 63,
    // REED
    SopranoSax = 64,
    AltoSax = 65,
    TenorSax = 66,
    BaritoneSax = 67,
    Oboe = 68,
    EnglishHorn = 69,
    Bassoon = 70,
    Clarinet = 71,
    // PIPE
    Piccolo = 72,
    Flute = 73,
    Recorder = 74,
    PanFlute = 75,
    BlownBottle = 76,
    Shakuhachi = 77,
    Whistle = 78,
    Ocarina = 79,
    // SYNTH LEAD
    Lead1square = 80,
    Lead2sawtooth = 81,
    Lead3calliope = 82,
    Lead4chiff = 83,
    Lead5charang = 84,
    Lead6voice = 85,
    Lead7fifths = 86,
    Lead8basslead = 87,
    // SYNTH PAD
    Pad1newage = 88,
    Pad2warm = 89,
    Pad3polysynth = 90,
    Pad4choir = 91,
    Pad5bowed = 92,
    Pad6metallic = 93,
    Pad7halo = 94,
    Pad8sweep = 95,
    //  SYNTH EFFECTS
    FX1rain = 96,
    FX2soundtrack = 97,
    FX3crystal = 98,
    FX4atmosphere = 99,
    FX5brightness = 100,
    FX6goblins = 101,
    FX7echoes = 102,
    FX8scifi = 103,
    // ETHNIC
    Sitar = 104,
    Banjo = 105,
    Shamisen = 106,
    Koto = 107,
    Kalimba = 108,
    Bagpipe = 109,
    Fiddle = 110,
    Shanai = 111,
    // PERCUSSIVE
    TinkleBell = 112,
    Agogo = 113,
    SteelDrums = 114,
    Woodblock = 115,
    TaikoDrum = 116,
    MelodicTom = 117,
    SynthDrum = 118,
    ReverseCymbal = 119,
    // SOUND EFFECTS
    GuitarFretNoise = 120,
    BreathNoise = 121,
    Seashore = 122,
    BirdTweet = 123,
    TelephoneRing = 124,
    Helicopter = 125,
    Applause = 126,
    Gunshot = 127,
    // Drum
    AcousticBassDrum = 0x80 + 35,
    BassDrum1 = 0x80 + 36,
    SideStick = 0x80 + 37,
    AcousticSnare = 0x80 + 38,
    HandClap = 0x80 + 39,
    ElectricSnare = 0x80 + 40,
    LowFloorTom = 0x80 + 41,
    ClosedHiHat = 0x80 + 42,
    HighFloorTom = 0x80 + 43,
    PedalHiHat = 0x80 + 44,
    LowTom = 0x80 + 45,
    OpenHiHat = 0x80 + 46,
    LowMidTom = 0x80 + 47,
    HiMidTom = 0x80 + 48,
    CrashCymbal1 = 0x80 + 49,
    HighTom = 0x80 + 50,
    RideCymbal1 = 0x80 + 51,
    ChineseCymbal = 0x80 + 52,
    RideBell = 0x80 + 53,
    Tambourine = 0x80 + 54,
    SplashCymbal = 0x80 + 55,
    Cowbell = 0x80 + 56,
    CrashCymbal2 = 0x80 + 57,
    Vibraslap = 0x80 + 58,
    RideCymbal2 = 0x80 + 59,
    HiBongo = 0x80 + 60,
    LowBongo = 0x80 + 61,
    MuteHiConga = 0x80 + 62,
    OpenHiConga = 0x80 + 63,
    LowConga = 0x80 + 64,
    HighTimbale = 0x80 + 65,
    LowTimbale = 0x80 + 66,
    HighAgogo = 0x80 + 67,
    LowAgogo = 0x80 + 68,
    Cabasa = 0x80 + 69,
    Maracas = 0x80 + 70,
    ShortWhistle = 0x80 + 71,
    LongWhistle = 0x80 + 72,
    ShortGuiro = 0x80 + 73,
    LongGuiro = 0x80 + 74,
    Claves = 0x80 + 75,
    HiWoodBlock = 0x80 + 76,
    LowWoodBlock = 0x80 + 77,
    MuteCuica = 0x80 + 78,
    OpenCuica = 0x80 + 79,
    MuteTriangle = 0x80 + 80,
    OpenTriangle = 0x80 + 81,
}

impl Program {
    pub const ALL: [Program; 175] = [
        Self::AcousticGrand,
        Self::BrightAcoustic,
        Self::ElectricGrand,
        Self::HonkyTonk,
        Self::ElectricPiano1,
        Self::ElectricPiano2,
        Self::Harpsichord,
        Self::Clavinet,
        Self::Celesta,
        Self::Glockenspiel,
        Self::MusicBox,
        Self::Vibraphone,
        Self::Marimba,
        Self::Xylophone,
        Self::TubularBells,
        Self::Dulcimer,
        Self::DrawbarOrgan,
        Self::PercussiveOrgan,
        Self::RockOrgan,
        Self::ChurchOrgan,
        Self::ReedOrgan,
        Self::Accordion,
        Self::Harmonica,
        Self::TangoAccordion,
        Self::NylonStringGuitar,
        Self::SteelStringGuitar,
        Self::ElectricJazzGuitar,
        Self::ElectricCleanGuitar,
        Self::ElectricMutedGuitar,
        Self::OverdrivenGuitar,
        Self::DistortionGuitar,
        Self::GuitarHarmonics,
        Self::AcousticBass,
        Self::FingerElectricBass,
        Self::PickElectricBass,
        Self::FretlessBass,
        Self::SlapBass1,
        Self::SlapBass2,
        Self::SynthBass1,
        Self::SynthBass2,
        Self::Violin,
        Self::Viola,
        Self::Cello,
        Self::Contrabass,
        Self::TremoloStrings,
        Self::PizzicatoStrings,
        Self::OrchestralHarp,
        Self::Timpani,
        Self::StringEnsemble1,
        Self::StringEnsemble2,
        Self::SynthStrings1,
        Self::SynthStrings2,
        Self::ChoirAahs,
        Self::VoiceOohs,
        Self::SynthVoice,
        Self::OrchestraHit,
        Self::Trumpet,
        Self::Trombone,
        Self::Tuba,
        Self::MutedTrumpet,
        Self::FrenchHorn,
        Self::BrassSection,
        Self::SynthBrass1,
        Self::SynthBrass2,
        Self::SopranoSax,
        Self::AltoSax,
        Self::TenorSax,
        Self::BaritoneSax,
        Self::Oboe,
        Self::EnglishHorn,
        Self::Bassoon,
        Self::Clarinet,
        Self::Piccolo,
        Self::Flute,
        Self::Recorder,
        Self::PanFlute,
        Self::BlownBottle,
        Self::Shakuhachi,
        Self::Whistle,
        Self::Ocarina,
        Self::Lead1square,
        Self::Lead2sawtooth,
        Self::Lead3calliope,
        Self::Lead4chiff,
        Self::Lead5charang,
        Self::Lead6voice,
        Self::Lead7fifths,
        Self::Lead8basslead,
        Self::Pad1newage,
        Self::Pad2warm,
        Self::Pad3polysynth,
        Self::Pad4choir,
        Self::Pad5bowed,
        Self::Pad6metallic,
        Self::Pad7halo,
        Self::Pad8sweep,
        Self::FX1rain,
        Self::FX2soundtrack,
        Self::FX3crystal,
        Self::FX4atmosphere,
        Self::FX5brightness,
        Self::FX6goblins,
        Self::FX7echoes,
        Self::FX8scifi,
        Self::Sitar,
        Self::Banjo,
        Self::Shamisen,
        Self::Koto,
        Self::Kalimba,
        Self::Bagpipe,
        Self::Fiddle,
        Self::Shanai,
        Self::TinkleBell,
        Self::Agogo,
        Self::SteelDrums,
        Self::Woodblock,
        Self::TaikoDrum,
        Self::MelodicTom,
        Self::SynthDrum,
        Self::ReverseCymbal,
        Self::GuitarFretNoise,
        Self::BreathNoise,
        Self::Seashore,
        Self::BirdTweet,
        Self::TelephoneRing,
        Self::Helicopter,
        Self::Applause,
        Self::Gunshot,
        Self::AcousticBassDrum,
        Self::BassDrum1,
        Self::SideStick,
        Self::AcousticSnare,
        Self::HandClap,
        Self::ElectricSnare,
        Self::LowFloorTom,
        Self::ClosedHiHat,
        Self::HighFloorTom,
        Self::PedalHiHat,
        Self::LowTom,
        Self::OpenHiHat,
        Self::LowMidTom,
        Self::HiMidTom,
        Self::CrashCymbal1,
        Self::HighTom,
        Self::RideCymbal1,
        Self::ChineseCymbal,
        Self::RideBell,
        Self::Tambourine,
        Self::SplashCymbal,
        Self::Cowbell,
        Self::CrashCymbal2,
        Self::Vibraslap,
        Self::RideCymbal2,
        Self::HiBongo,
        Self::LowBongo,
        Self::MuteHiConga,
        Self::OpenHiConga,
        Self::LowConga,
        Self::HighTimbale,
        Self::LowTimbale,
        Self::HighAgogo,
        Self::LowAgogo,
        Self::Cabasa,
        Self::Maracas,
        Self::ShortWhistle,
        Self::LongWhistle,
        Self::ShortGuiro,
        Self::LongGuiro,
        Self::Claves,
        Self::HiWoodBlock,
        Self::LowWoodBlock,
        Self::MuteCuica,
        Self::OpenCuica,
        Self::MuteTriangle,
        Self::OpenTriangle,
    ];
}

impl std::fmt::Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::AcousticGrand => "1 Acoustic Grand",
            Self::BrightAcoustic => "2 Bright Acoustic",
            Self::ElectricGrand => "3 Electric Grand Piano",
            Self::HonkyTonk => "4 Honky-Tonk Piano",
            Self::ElectricPiano1 => "5 Electric Piano",
            Self::ElectricPiano2 => "6 Electric Piano 2",
            Self::Harpsichord => "7 Harpsichord",
            Self::Clavinet => "8 Clavinet",
            Self::Celesta => "9 Celesta",
            Self::Glockenspiel => "10 Glockenspiel",
            Self::MusicBox => "11 Music Box",
            Self::Vibraphone => "12 Vibraphone",
            Self::Marimba => "13 Marimba",
            Self::Xylophone => "14 Xylophone",
            Self::TubularBells => "15 Tubular Bells",
            Self::Dulcimer => "16 Dulcimer",
            Self::DrawbarOrgan => "17 Drawbar Organ",
            Self::PercussiveOrgan => "18 Percussive Organ",
            Self::RockOrgan => "19 Rock Organ",
            Self::ChurchOrgan => "20 Church Organ",
            Self::ReedOrgan => "21 Reed Organ",
            Self::Accordion => "22 Accordion",
            Self::Harmonica => "23 Harmonica",
            Self::TangoAccordion => "24 Tango Accordion",
            Self::NylonStringGuitar => "25 String Guitar (nylon)",
            Self::SteelStringGuitar => "26 String Guitar (steel)",
            Self::ElectricJazzGuitar => "27 Electric Guitar (jazz)",
            Self::ElectricCleanGuitar => "28 Electric Guitar (clean)",
            Self::ElectricMutedGuitar => "29 Electric Guitar (muted)",
            Self::OverdrivenGuitar => "30 Overdriven Guitar",
            Self::DistortionGuitar => "31 Distortion Guitar",
            Self::GuitarHarmonics => "32 Guitar Harmonics",
            Self::AcousticBass => "33 Acoustic Bass",
            Self::FingerElectricBass => "34 Electric Bass (finger)",
            Self::PickElectricBass => "35 Electric Bass (pick)",
            Self::FretlessBass => "36 Fretless Bass",
            Self::SlapBass1 => "37 Slap Bass 1",
            Self::SlapBass2 => "38 Slap Bass 2",
            Self::SynthBass1 => "39 Synth Bass 1",
            Self::SynthBass2 => "40 Synth Bass 2",
            Self::Violin => "41 Violin",
            Self::Viola => "42 Viola",
            Self::Cello => "43 Cello",
            Self::Contrabass => "44 Contrabass",
            Self::TremoloStrings => "45 Tremolo Strings",
            Self::PizzicatoStrings => "46 Pizzicato Strings",
            Self::OrchestralHarp => "47 Orchestral Harp",
            Self::Timpani => "48 Timpani",
            Self::StringEnsemble1 => "49 String Ensemble 1",
            Self::StringEnsemble2 => "50 String Ensemble 2",
            Self::SynthStrings1 => "51 Synth Strings 1",
            Self::SynthStrings2 => "52 Synth Strings 2",
            Self::ChoirAahs => "53 Choir Aahs",
            Self::VoiceOohs => "54 Voice Oohs",
            Self::SynthVoice => "55 Synth Voice",
            Self::OrchestraHit => "56 Orchestra Hit",
            Self::Trumpet => "57 Trumpet",
            Self::Trombone => "58 Trombone",
            Self::Tuba => "59 Tuba",
            Self::MutedTrumpet => "60 Muted Trumpet",
            Self::FrenchHorn => "61 French Horn",
            Self::BrassSection => "62 Brass Section",
            Self::SynthBrass1 => "63 Synth Brass 1",
            Self::SynthBrass2 => "64 Synth Brass 2",
            Self::SopranoSax => "65 Soprano Sax",
            Self::AltoSax => "66 Alto Sax",
            Self::TenorSax => "67 Tenor Sax",
            Self::BaritoneSax => "68 Baritone Sax",
            Self::Oboe => "69 Oboe",
            Self::EnglishHorn => "70 English Horn",
            Self::Bassoon => "71 Bassoon",
            Self::Clarinet => "72 Clarinet",
            Self::Piccolo => "73 Piccolo",
            Self::Flute => "74 Flute",
            Self::Recorder => "75 Recorder",
            Self::PanFlute => "76 Pan Flute",
            Self::BlownBottle => "77 Blown Bottle",
            Self::Shakuhachi => "78 Shakuhachi",
            Self::Whistle => "79 Whistle",
            Self::Ocarina => "80 Ocarina",
            Self::Lead1square => "81 Lead 1 (square)",
            Self::Lead2sawtooth => "82 Lead 2 (sawtooth)",
            Self::Lead3calliope => "83 Lead 3 (calliope)",
            Self::Lead4chiff => "84 Lead 4 (chiff)",
            Self::Lead5charang => "85 Lead 5 (charang)",
            Self::Lead6voice => "86 Lead 6 (voice)",
            Self::Lead7fifths => "87 Lead 7 (fifths)",
            Self::Lead8basslead => "88 Lead 8 (bass+lead)",
            Self::Pad1newage => "89 Pad 1 (newage)",
            Self::Pad2warm => "90 Pad 2 (warm)",
            Self::Pad3polysynth => "91 Pad 3 (polysynth)",
            Self::Pad4choir => "92 Pad 4 (choir)",
            Self::Pad5bowed => "93 Pad 5 (bowed)",
            Self::Pad6metallic => "94 Pad 6 (metallic)",
            Self::Pad7halo => "95 Pad 7 (halo)",
            Self::Pad8sweep => "96 Pad 8 (sweep)",
            Self::FX1rain => "97 FX 1 (rain)",
            Self::FX2soundtrack => "98 FX 2 (soundtrack)",
            Self::FX3crystal => "99 FX 3 (crystal)",
            Self::FX4atmosphere => "100 FX 4 (atmosphere)",
            Self::FX5brightness => "101 FX 5 (brightness)",
            Self::FX6goblins => "102 FX 6 (goblins)",
            Self::FX7echoes => "103 FX 7 (echoes)",
            Self::FX8scifi => "104 FX 8 (sci-fi)",
            Self::Sitar => "105 Sitar",
            Self::Banjo => "106 Banjo",
            Self::Shamisen => "107 Shamisen",
            Self::Koto => "108 Koto",
            Self::Kalimba => "109 Kalimba",
            Self::Bagpipe => "110 Bagpipe",
            Self::Fiddle => "111 Fiddle",
            Self::Shanai => "112 Shanai",
            Self::TinkleBell => "113 Tinkle Bell",
            Self::Agogo => "114 Agogo",
            Self::SteelDrums => "115 Steel Drums",
            Self::Woodblock => "116 Woodblock",
            Self::TaikoDrum => "117 Taiko Drum",
            Self::MelodicTom => "118 Melodic Tom",
            Self::SynthDrum => "119 Synth Drum",
            Self::ReverseCymbal => "120 Reverse Cymbal",
            Self::GuitarFretNoise => "121 Guitar Fret Noise",
            Self::BreathNoise => "122 Breath Noise",
            Self::Seashore => "123 Seashore",
            Self::BirdTweet => "124 Bird Tweet",
            Self::TelephoneRing => "125 Telephone Ring",
            Self::Helicopter => "126 Helicopter",
            Self::Applause => "127 Applause",
            Self::Gunshot => "128 Gunshot",
            Self::AcousticBassDrum => "D35 Acoustic Bass Drum",
            Self::BassDrum1 => "D36 Bass Drum 1",
            Self::SideStick => "D37 Side Stick",
            Self::AcousticSnare => "D38 Acoustic Snare",
            Self::HandClap => "D39 Hand Clap",
            Self::ElectricSnare => "D40 Electric Snare",
            Self::LowFloorTom => "D41 Low Floor Tom",
            Self::ClosedHiHat => "D42 Closed Hi-Hat",
            Self::HighFloorTom => "D43 High Floor Tom",
            Self::PedalHiHat => "D44 Pedal Hi-Hat",
            Self::LowTom => "D45 Low Tom",
            Self::OpenHiHat => "D46 Open Hi-Hat",
            Self::LowMidTom => "D47 Low-Mid Tom",
            Self::HiMidTom => "D48 Hi-Mid Tom",
            Self::CrashCymbal1 => "D49 Crash Cymbal 1",
            Self::HighTom => "D50 High Tom",
            Self::RideCymbal1 => "D51 Ride Cymbal 1",
            Self::ChineseCymbal => "D52 Chinese Cymbal",
            Self::RideBell => "D53 Ride Bell",
            Self::Tambourine => "D54 Tambourine",
            Self::SplashCymbal => "D55 Splash Cymbal",
            Self::Cowbell => "D56 Cowbell",
            Self::CrashCymbal2 => "D57 Crash Cymbal 2",
            Self::Vibraslap => "D58 Vibraslap",
            Self::RideCymbal2 => "D59 Ride Cymbal 2",
            Self::HiBongo => "D60 Hi Bongo",
            Self::LowBongo => "D61 Low Bongo",
            Self::MuteHiConga => "D62 Mute Hi Conga",
            Self::OpenHiConga => "D63 Open Hi Conga",
            Self::LowConga => "D64 Low Conga",
            Self::HighTimbale => "D65 High Timbale",
            Self::LowTimbale => "D66 Low Timbale",
            Self::HighAgogo => "D67 High Agogo",
            Self::LowAgogo => "D68 Low Agogo",
            Self::Cabasa => "D69 Cabasa",
            Self::Maracas => "D70 Maracas",
            Self::ShortWhistle => "D71 Short Whistle",
            Self::LongWhistle => "D72 Long Whistle",
            Self::ShortGuiro => "D73 Short Guiro",
            Self::LongGuiro => "D74 Long Guiro",
            Self::Claves => "D75 Claves",
            Self::HiWoodBlock => "D76 Hi Wood Block",
            Self::LowWoodBlock => "D77 Low Wood Block",
            Self::MuteCuica => "D78 Mute Cuica",
            Self::OpenCuica => "D79 Open Cuica",
            Self::MuteTriangle => "D80 Mute Triangle",
            Self::OpenTriangle => "D81 Open Triangle",
        })
    }
}

impl TryFrom<u8> for Program {
    type Error = &'static str;

    fn try_from(value: u8) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::AcousticGrand),
            1 => Ok(Self::BrightAcoustic),
            2 => Ok(Self::ElectricGrand),
            3 => Ok(Self::HonkyTonk),
            4 => Ok(Self::ElectricPiano1),
            5 => Ok(Self::ElectricPiano2),
            6 => Ok(Self::Harpsichord),
            7 => Ok(Self::Clavinet),
            8 => Ok(Self::Celesta),
            9 => Ok(Self::Glockenspiel),
            10 => Ok(Self::MusicBox),
            11 => Ok(Self::Vibraphone),
            12 => Ok(Self::Marimba),
            13 => Ok(Self::Xylophone),
            14 => Ok(Self::TubularBells),
            15 => Ok(Self::Dulcimer),
            16 => Ok(Self::DrawbarOrgan),
            17 => Ok(Self::PercussiveOrgan),
            18 => Ok(Self::RockOrgan),
            19 => Ok(Self::ChurchOrgan),
            20 => Ok(Self::ReedOrgan),
            21 => Ok(Self::Accordion),
            22 => Ok(Self::Harmonica),
            23 => Ok(Self::TangoAccordion),
            24 => Ok(Self::NylonStringGuitar),
            25 => Ok(Self::SteelStringGuitar),
            26 => Ok(Self::ElectricJazzGuitar),
            27 => Ok(Self::ElectricCleanGuitar),
            28 => Ok(Self::ElectricMutedGuitar),
            29 => Ok(Self::OverdrivenGuitar),
            30 => Ok(Self::DistortionGuitar),
            31 => Ok(Self::GuitarHarmonics),
            32 => Ok(Self::AcousticBass),
            33 => Ok(Self::FingerElectricBass),
            34 => Ok(Self::PickElectricBass),
            35 => Ok(Self::FretlessBass),
            36 => Ok(Self::SlapBass1),
            37 => Ok(Self::SlapBass2),
            38 => Ok(Self::SynthBass1),
            39 => Ok(Self::SynthBass2),
            40 => Ok(Self::Violin),
            41 => Ok(Self::Viola),
            42 => Ok(Self::Cello),
            43 => Ok(Self::Contrabass),
            44 => Ok(Self::TremoloStrings),
            45 => Ok(Self::PizzicatoStrings),
            46 => Ok(Self::OrchestralHarp),
            47 => Ok(Self::Timpani),
            48 => Ok(Self::StringEnsemble1),
            49 => Ok(Self::StringEnsemble2),
            50 => Ok(Self::SynthStrings1),
            51 => Ok(Self::SynthStrings2),
            52 => Ok(Self::ChoirAahs),
            53 => Ok(Self::VoiceOohs),
            54 => Ok(Self::SynthVoice),
            55 => Ok(Self::OrchestraHit),
            56 => Ok(Self::Trumpet),
            57 => Ok(Self::Trombone),
            58 => Ok(Self::Tuba),
            59 => Ok(Self::MutedTrumpet),
            60 => Ok(Self::FrenchHorn),
            61 => Ok(Self::BrassSection),
            62 => Ok(Self::SynthBrass1),
            63 => Ok(Self::SynthBrass2),
            64 => Ok(Self::SopranoSax),
            65 => Ok(Self::AltoSax),
            66 => Ok(Self::TenorSax),
            67 => Ok(Self::BaritoneSax),
            68 => Ok(Self::Oboe),
            69 => Ok(Self::EnglishHorn),
            70 => Ok(Self::Bassoon),
            71 => Ok(Self::Clarinet),
            72 => Ok(Self::Piccolo),
            73 => Ok(Self::Flute),
            74 => Ok(Self::Recorder),
            75 => Ok(Self::PanFlute),
            76 => Ok(Self::BlownBottle),
            77 => Ok(Self::Shakuhachi),
            78 => Ok(Self::Whistle),
            79 => Ok(Self::Ocarina),
            80 => Ok(Self::Lead1square),
            81 => Ok(Self::Lead2sawtooth),
            82 => Ok(Self::Lead3calliope),
            83 => Ok(Self::Lead4chiff),
            84 => Ok(Self::Lead5charang),
            85 => Ok(Self::Lead6voice),
            86 => Ok(Self::Lead7fifths),
            87 => Ok(Self::Lead8basslead),
            88 => Ok(Self::Pad1newage),
            89 => Ok(Self::Pad2warm),
            90 => Ok(Self::Pad3polysynth),
            91 => Ok(Self::Pad4choir),
            92 => Ok(Self::Pad5bowed),
            93 => Ok(Self::Pad6metallic),
            94 => Ok(Self::Pad7halo),
            95 => Ok(Self::Pad8sweep),
            96 => Ok(Self::FX1rain),
            97 => Ok(Self::FX2soundtrack),
            98 => Ok(Self::FX3crystal),
            99 => Ok(Self::FX4atmosphere),
            100 => Ok(Self::FX5brightness),
            101 => Ok(Self::FX6goblins),
            102 => Ok(Self::FX7echoes),
            103 => Ok(Self::FX8scifi),
            104 => Ok(Self::Sitar),
            105 => Ok(Self::Banjo),
            106 => Ok(Self::Shamisen),
            107 => Ok(Self::Koto),
            108 => Ok(Self::Kalimba),
            109 => Ok(Self::Bagpipe),
            110 => Ok(Self::Fiddle),
            111 => Ok(Self::Shanai),
            112 => Ok(Self::TinkleBell),
            113 => Ok(Self::Agogo),
            114 => Ok(Self::SteelDrums),
            115 => Ok(Self::Woodblock),
            116 => Ok(Self::TaikoDrum),
            117 => Ok(Self::MelodicTom),
            118 => Ok(Self::SynthDrum),
            119 => Ok(Self::ReverseCymbal),
            120 => Ok(Self::GuitarFretNoise),
            121 => Ok(Self::BreathNoise),
            122 => Ok(Self::Seashore),
            123 => Ok(Self::BirdTweet),
            124 => Ok(Self::TelephoneRing),
            125 => Ok(Self::Helicopter),
            126 => Ok(Self::Applause),
            127 => Ok(Self::Gunshot),
            163 => Ok(Self::AcousticBassDrum),
            164 => Ok(Self::BassDrum1),
            165 => Ok(Self::SideStick),
            166 => Ok(Self::AcousticSnare),
            167 => Ok(Self::HandClap),
            168 => Ok(Self::ElectricSnare),
            169 => Ok(Self::LowFloorTom),
            170 => Ok(Self::ClosedHiHat),
            171 => Ok(Self::HighFloorTom),
            172 => Ok(Self::PedalHiHat),
            173 => Ok(Self::LowTom),
            174 => Ok(Self::OpenHiHat),
            175 => Ok(Self::LowMidTom),
            176 => Ok(Self::HiMidTom),
            177 => Ok(Self::CrashCymbal1),
            178 => Ok(Self::HighTom),
            179 => Ok(Self::RideCymbal1),
            180 => Ok(Self::ChineseCymbal),
            181 => Ok(Self::RideBell),
            182 => Ok(Self::Tambourine),
            183 => Ok(Self::SplashCymbal),
            184 => Ok(Self::Cowbell),
            185 => Ok(Self::CrashCymbal2),
            186 => Ok(Self::Vibraslap),
            187 => Ok(Self::RideCymbal2),
            188 => Ok(Self::HiBongo),
            189 => Ok(Self::LowBongo),
            190 => Ok(Self::MuteHiConga),
            191 => Ok(Self::OpenHiConga),
            192 => Ok(Self::LowConga),
            193 => Ok(Self::HighTimbale),
            194 => Ok(Self::LowTimbale),
            195 => Ok(Self::HighAgogo),
            196 => Ok(Self::LowAgogo),
            197 => Ok(Self::Cabasa),
            198 => Ok(Self::Maracas),
            199 => Ok(Self::ShortWhistle),
            200 => Ok(Self::LongWhistle),
            201 => Ok(Self::ShortGuiro),
            202 => Ok(Self::LongGuiro),
            203 => Ok(Self::Claves),
            204 => Ok(Self::HiWoodBlock),
            205 => Ok(Self::LowWoodBlock),
            206 => Ok(Self::MuteCuica),
            207 => Ok(Self::OpenCuica),
            208 => Ok(Self::MuteTriangle),
            209 => Ok(Self::OpenTriangle),
            _ => Err("Invalid program number"),
        }
    }
}
