#[repr(u8)]
#[derive(Debug,Clone)]
pub enum Program {
    // PIANO
    AcousticGrand = 0,
    BrightAcoustic = 1,
    ElectricGrand = 2,
    HonkyTonk = 3,
    ElectricPiano1 = 4,
    ElectricPiano2 = 5,
    Harpsichord = 6,
    Clavinet = 7,
    // CHROMATIC PERCUSSION
    Celesta = 8,
    Glockenspiel = 9,
    MusicBox = 10,
    Vibraphone = 11,
    Marimba = 12,
    Xylophone = 13,
    TubularBells = 14,
    Dulcimer = 15,
    // ORGAN
    DrawbarOrgan = 16,
    PercussiveOrgan = 17,
    RockOrgan = 18,
    ChurchOrgan = 19,
    ReedOrgan = 20,
    Accoridan = 21,
    Harmonica = 22,
    TangoAccordian = 23,
    // GUITAR
    NylonStringGuitar = 24,
    SteelStringGuitar = 25,
    ElectricJazzGuitar = 26,
    ElectricCleanGuitar = 27,
    ElectricMutedGuitar = 28,
    OverdrivenGuitar = 29,
    DistortionGuitar = 30,
    GuitarHarmonics = 31,
    // BASS
    AcousticBass = 32,
    FingerElectricBass = 33,
    PickElectricBass = 34,
    FretlessBass = 35,
    SlapBass1 = 36,
    SlapBass2 = 37,
    SynthBass1 = 38,
    SynthBass2 = 39,
    // SOLO STRINGS
    Violin = 40,
    Viola = 41,
    Cello = 42,
    Contrabass = 43,
    TremoloStrings = 44,
    PizzicatoStrings = 45,
    OrchestralStrings = 46,
    Timpani = 47,
    // ENSEMBLE
    StringEnsemble1 = 48,
    StringEnsemble2 = 49,
    SynthStrings1 = 50,
    SynthStrings2 = 51,
    ChoirAahs = 52,
    VoiceOohs = 53,
    SynthVoice = 54,
    OrchestraHit = 55,
    // BRASS
    Trumpet = 56,
    Trombone = 57,
    Tuba = 58,
    MutedTrumpet = 59,
    FrenchHorn = 60,
    BrassSection = 61,
    SynthBrass1 = 62,
    SynthBrass2 = 63,
    // REED
    SopranoSax = 64,
    AltoSax = 65,
    TenorSax = 66,
    BaritoneSax = 67,
    Oboe = 68,
    EnglishHorn = 69,
    Bassoon = 70,
    Clarinet = 71,
    // PIPE
    Piccolo = 72,
    Flute = 73,
    Recorder = 74,
    PanFlute = 75,
    BlownBottle = 76,
    Shakuhachi = 77,
    Whistle = 78,
    Ocarina = 79,
    // SYNTH LEAD
    Lead1square = 80,
    Lead2sawtooth = 81,
    Lead3calliope = 82,
    Lead4chiff = 83,
    Lead5charang = 84,
    Lead6voice = 85,
    Lead7fifths = 86,
    Lead8basslead = 87,
    // SYNTH PAD
    Pad1newage = 88,
    Pad2warm = 89,
    Pad3polysynth = 90,
    Pad4choir = 91,
    Pad5bowed = 92,
    Pad6metallic = 93,
    Pad7halo = 94,
    Pad8sweep = 95,
    //  SYNTH EFFECTS
    FX1rain = 96,
    FX2soundtrack = 97,
    FX3crystal = 98,
    FX4atmosphere = 99,
    FX5brightness = 100,
    FX6goblins = 101,
    FX7echoes = 102,
    FX8scifi = 103,
    // ETHNIC
    Sitar = 104,
    Banjo = 105,
    Shamisen = 106,
    Koto = 107,
    Kalimba = 108,
    Bagpipe = 109,
    Fiddle = 110,
    Shanai = 111,
    // PERCUSSIVE
    TinkleBell = 112,
    Agogo = 113,
    SteelDrums = 114,
    Woodblock = 115,
    TaikoDrum = 116,
    MelodicTom = 117,
    SynthDrum = 118,
    ReverseCymbal = 119,
    // SOUND EFFECTS
    GuitarFretNoise = 120,
    BreathNoise = 121,
    Seashore = 122,
    BirdTweet = 123,
    TelephoneRing = 124,
    Helicopter = 125,
    Applause = 126,
    Gunshot = 127,
    // Drum
    AcousticBassDrum = 0x80 + 35,
    BassDrum1 = 0x80 + 36,
    SideStick = 0x80 + 37,
    AcousticSnare = 0x80 + 38,
    HandClap = 0x80 + 39,
    ElectricSnare = 0x80 + 40,
    LowFloorTom = 0x80 + 41,
    ClosedHiHat = 0x80 + 42,
    HighFloorTom = 0x80 + 43,
    PedalHiHat = 0x80 + 44,
    LowTom = 0x80 + 45,
    OpenHiHat = 0x80 + 46,
    LowMidTom = 0x80 + 47,
    HiMidTom = 0x80 + 48,
    CrashCymbal1 = 0x80 + 49,
    HighTom = 0x80 + 50,
    RideCymbal1 = 0x80 + 51,
    ChineseCymbal = 0x80 + 52,
    RideBell = 0x80 + 53,
    Tambourine = 0x80 + 54,
    SplashCymbal = 0x80 + 55,
    Cowbell = 0x80 + 56,
    CrashCymbal2 = 0x80 + 57,
    Vibraslap = 0x80 + 58,
    RideCymbal2 = 0x80 + 59,
    HiBongo = 0x80 + 60,
    LowBongo = 0x80 + 61,
    MuteHiConga = 0x80 + 62,
    OpenHiConga = 0x80 + 63,
    LowConga = 0x80 + 64,
    HighTimbale = 0x80 + 65,
    LowTimbale = 0x80 + 66,
    HighAgogo = 0x80 + 67,
    LowAgogo = 0x80 + 68,
    Cabasa = 0x80 + 69,
    Maracas = 0x80 + 70,
    ShortWhistle = 0x80 + 71,
    LongWhistle = 0x80 + 72,
    ShortGuiro = 0x80 + 73,
    LongGuiro = 0x80 + 74,
    Claves = 0x80 + 75,
    HiWoodBlock = 0x80 + 76,
    LowWoodBlock = 0x80 + 77,
    MuteCuica = 0x80 + 78,
    OpenCuica = 0x80 + 79,
    MuteTriangle = 0x80 + 80,
    OpenTriangle = 0x80 + 81,
}

impl Program {
    pub const ALL: [Program; 175] = [
        Self::AcousticGrand,
        Self::BrightAcoustic,
        Self::ElectricGrand,
        Self::HonkyTonk,
        Self::ElectricPiano1,
        Self::ElectricPiano2,
        Self::Harpsichord,
        Self::Clavinet,
        Self::Celesta,
        Self::Glockenspiel,
        Self::MusicBox,
        Self::Vibraphone,
        Self::Marimba,
        Self::Xylophone,
        Self::TubularBells,
        Self::Dulcimer,
        Self::DrawbarOrgan,
        Self::PercussiveOrgan,
        Self::RockOrgan,
        Self::ChurchOrgan,
        Self::ReedOrgan,
        Self::Accoridan,
        Self::Harmonica,
        Self::TangoAccordian,
        Self::NylonStringGuitar,
        Self::SteelStringGuitar,
        Self::ElectricJazzGuitar,
        Self::ElectricCleanGuitar,
        Self::ElectricMutedGuitar,
        Self::OverdrivenGuitar,
        Self::DistortionGuitar,
        Self::GuitarHarmonics,
        Self::AcousticBass,
        Self::FingerElectricBass,
        Self::PickElectricBass,
        Self::FretlessBass,
        Self::SlapBass1,
        Self::SlapBass2,
        Self::SynthBass1,
        Self::SynthBass2,
        Self::Violin,
        Self::Viola,
        Self::Cello,
        Self::Contrabass,
        Self::TremoloStrings,
        Self::PizzicatoStrings,
        Self::OrchestralStrings,
        Self::Timpani,
        Self::StringEnsemble1,
        Self::StringEnsemble2,
        Self::SynthStrings1,
        Self::SynthStrings2,
        Self::ChoirAahs,
        Self::VoiceOohs,
        Self::SynthVoice,
        Self::OrchestraHit,
        Self::Trumpet,
        Self::Trombone,
        Self::Tuba,
        Self::MutedTrumpet,
        Self::FrenchHorn,
        Self::BrassSection,
        Self::SynthBrass1,
        Self::SynthBrass2,
        Self::SopranoSax,
        Self::AltoSax,
        Self::TenorSax,
        Self::BaritoneSax,
        Self::Oboe,
        Self::EnglishHorn,
        Self::Bassoon,
        Self::Clarinet,
        Self::Piccolo,
        Self::Flute,
        Self::Recorder,
        Self::PanFlute,
        Self::BlownBottle,
        Self::Shakuhachi,
        Self::Whistle,
        Self::Ocarina,
        Self::Lead1square,
        Self::Lead2sawtooth,
        Self::Lead3calliope,
        Self::Lead4chiff,
        Self::Lead5charang,
        Self::Lead6voice,
        Self::Lead7fifths,
        Self::Lead8basslead,
        Self::Pad1newage,
        Self::Pad2warm,
        Self::Pad3polysynth,
        Self::Pad4choir,
        Self::Pad5bowed,
        Self::Pad6metallic,
        Self::Pad7halo,
        Self::Pad8sweep,
        Self::FX1rain,
        Self::FX2soundtrack,
        Self::FX3crystal,
        Self::FX4atmosphere,
        Self::FX5brightness,
        Self::FX6goblins,
        Self::FX7echoes,
        Self::FX8scifi,
        Self::Sitar,
        Self::Banjo,
        Self::Shamisen,
        Self::Koto,
        Self::Kalimba,
        Self::Bagpipe,
        Self::Fiddle,
        Self::Shanai,
        Self::TinkleBell,
        Self::Agogo,
        Self::SteelDrums,
        Self::Woodblock,
        Self::TaikoDrum,
        Self::MelodicTom,
        Self::SynthDrum,
        Self::ReverseCymbal,
        Self::GuitarFretNoise,
        Self::BreathNoise,
        Self::Seashore,
        Self::BirdTweet,
        Self::TelephoneRing,
        Self::Helicopter,
        Self::Applause,
        Self::Gunshot,
        Self::AcousticBassDrum,
        Self::BassDrum1,
        Self::SideStick,
        Self::AcousticSnare,
        Self::HandClap,
        Self::ElectricSnare,
        Self::LowFloorTom,
        Self::ClosedHiHat,
        Self::HighFloorTom,
        Self::PedalHiHat,
        Self::LowTom,
        Self::OpenHiHat,
        Self::LowMidTom,
        Self::HiMidTom,
        Self::CrashCymbal1,
        Self::HighTom,
        Self::RideCymbal1,
        Self::ChineseCymbal,
        Self::RideBell,
        Self::Tambourine,
        Self::SplashCymbal,
        Self::Cowbell,
        Self::CrashCymbal2,
        Self::Vibraslap,
        Self::RideCymbal2,
        Self::HiBongo,
        Self::LowBongo,
        Self::MuteHiConga,
        Self::OpenHiConga,
        Self::LowConga,
        Self::HighTimbale,
        Self::LowTimbale,
        Self::HighAgogo,
        Self::LowAgogo,
        Self::Cabasa,
        Self::Maracas,
        Self::ShortWhistle,
        Self::LongWhistle,
        Self::ShortGuiro,
        Self::LongGuiro,
        Self::Claves,
        Self::HiWoodBlock,
        Self::LowWoodBlock,
        Self::MuteCuica,
        Self::OpenCuica,
        Self::MuteTriangle,
        Self::OpenTriangle,
    ];
}

impl std::fmt::Display for Program {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(match self {
            Self::AcousticGrand => "Acoustic Grand",
            Self::BrightAcoustic => "Bright Acoustic",
            Self::ElectricGrand => "Electric Grand Piano",
            Self::HonkyTonk => "Honky-Tonk Piano",
            Self::ElectricPiano1 => "Electric Piano",
            Self::ElectricPiano2 => "Electric Piano 2",
            Self::Harpsichord => "Harpsichord",
            Self::Clavinet => "Clavinet",
            Self::Celesta => "Celesta",
            Self::Glockenspiel => "Glockenspiel",
            Self::MusicBox => "Music Box",
            Self::Vibraphone => "Vibraphone",
            Self::Marimba => "Marimba",
            Self::Xylophone => "Xylophone",
            Self::TubularBells => "Tubular Bells",
            Self::Dulcimer => "Dulcimer",
            Self::DrawbarOrgan => "Drawbar Organ",
            Self::PercussiveOrgan => "Percussive Organ",
            Self::RockOrgan => "Rock Organ",
            Self::ChurchOrgan => "Church Organ",
            Self::ReedOrgan => "Reed Organ",
            Self::Accoridan => "Accoridan",
            Self::Harmonica => "Harmonica",
            Self::TangoAccordian => "Tango Accordian",
            Self::NylonStringGuitar => "String Guitar (nylon)",
            Self::SteelStringGuitar => "String Guitar (steel)",
            Self::ElectricJazzGuitar => "Electric Guitar (jazz)",
            Self::ElectricCleanGuitar => "Electric Guitar (clean)",
            Self::ElectricMutedGuitar => "Electric Guitar (muted)",
            Self::OverdrivenGuitar => "Overdriven Guitar",
            Self::DistortionGuitar => "Distortion Guitar",
            Self::GuitarHarmonics => "Guitar Harmonics",
            Self::AcousticBass => "Acoustic Bass",
            Self::FingerElectricBass => "Electric Bass (finger)",
            Self::PickElectricBass => "Electric Bass (pick)",
            Self::FretlessBass => "Fretless Bass",
            Self::SlapBass1 => "Slap Bass 1",
            Self::SlapBass2 => "Slap Bass 2",
            Self::SynthBass1 => "Synth Bass 1",
            Self::SynthBass2 => "Synth Bass 2",
            Self::Violin => "Violin",
            Self::Viola => "Viola",
            Self::Cello => "Cello",
            Self::Contrabass => "Contrabass",
            Self::TremoloStrings => "Tremolo Strings",
            Self::PizzicatoStrings => "Pizzicato Strings",
            Self::OrchestralStrings => "Orchestral Strings",
            Self::Timpani => "Timpani",
            Self::StringEnsemble1 => "String Ensemble 1",
            Self::StringEnsemble2 => "String Ensemble 2",
            Self::SynthStrings1 => "Synth Strings 1",
            Self::SynthStrings2 => "Synth Strings 2",
            Self::ChoirAahs => "Choir Aahs",
            Self::VoiceOohs => "Voice Oohs",
            Self::SynthVoice => "Synth Voice",
            Self::OrchestraHit => "Orchestra Hit",
            Self::Trumpet => "Trumpet",
            Self::Trombone => "Trombone",
            Self::Tuba => "Tuba",
            Self::MutedTrumpet => "Muted Trumpet",
            Self::FrenchHorn => "French Horn",
            Self::BrassSection => "Brass Section",
            Self::SynthBrass1 => "Synth Brass 1",
            Self::SynthBrass2 => "Synth Brass 2",
            Self::SopranoSax => "Soprano Sax",
            Self::AltoSax => "Alto Sax",
            Self::TenorSax => "Tenor Sax",
            Self::BaritoneSax => "Baritone Sax",
            Self::Oboe => "Oboe",
            Self::EnglishHorn => "English Horn",
            Self::Bassoon => "Bassoon",
            Self::Clarinet => "Clarinet",
            Self::Piccolo => "Piccolo",
            Self::Flute => "Flute",
            Self::Recorder => "Recorder",
            Self::PanFlute => "Pan Flute",
            Self::BlownBottle => "Blown Bottle",
            Self::Shakuhachi => "Shakuhachi",
            Self::Whistle => "Whistle",
            Self::Ocarina => "Ocarina",
            Self::Lead1square => "Lead 1 (square)",
            Self::Lead2sawtooth => "Lead 2 (sawtooth)",
            Self::Lead3calliope => "Lead 3 (calliope)",
            Self::Lead4chiff => "Lead 4 (chiff)",
            Self::Lead5charang => "Lead 5 (charang)",
            Self::Lead6voice => "Lead 6 (voice)",
            Self::Lead7fifths => "Lead 7 (fifths)",
            Self::Lead8basslead => "Lead 8 (bass+lead)",
            Self::Pad1newage => "Pad 1 (newage)",
            Self::Pad2warm => "Pad 2 (warm)",
            Self::Pad3polysynth => "Pad 3 (polysynth)",
            Self::Pad4choir => "Pad 4 (choir)",
            Self::Pad5bowed => "Pad 5 (bowed)",
            Self::Pad6metallic => "Pad 6 (metallic)",
            Self::Pad7halo => "Pad 7 (halo)",
            Self::Pad8sweep => "Pad 8 (sweep)",
            Self::FX1rain => "FX 1 (rain)",
            Self::FX2soundtrack => "FX 2 (soundtrack)",
            Self::FX3crystal => "FX 3 (crystal)",
            Self::FX4atmosphere => "FX 4 (atmosphere)",
            Self::FX5brightness => "FX 5 (brightness)",
            Self::FX6goblins => "FX 6 (goblins)",
            Self::FX7echoes => "FX 7 (echoes)",
            Self::FX8scifi => "FX 8 (sci-fi)",
            Self::Sitar => "Sitar",
            Self::Banjo => "Banjo",
            Self::Shamisen => "Shamisen",
            Self::Koto => "Koto",
            Self::Kalimba => "Kalimba",
            Self::Bagpipe => "Bagpipe",
            Self::Fiddle => "Fiddle",
            Self::Shanai => "Shanai",
            Self::TinkleBell => "Tinkle Bell",
            Self::Agogo => "Agogo",
            Self::SteelDrums => "Steel Drums",
            Self::Woodblock => "Woodblock",
            Self::TaikoDrum => "Taiko Drum",
            Self::MelodicTom => "Melodic Tom",
            Self::SynthDrum => "Synth Drum",
            Self::ReverseCymbal => "Reverse Cymbal",
            Self::GuitarFretNoise => "Guitar Fret Noise",
            Self::BreathNoise => "Breath Noise",
            Self::Seashore => "Seashore",
            Self::BirdTweet => "Bird Tweet",
            Self::TelephoneRing => "Telephone Ring",
            Self::Helicopter => "Helicopter",
            Self::Applause => "Applause",
            Self::Gunshot => "Gunshot",
            Self::AcousticBassDrum => "Acoustic Bass Drum",
            Self::BassDrum1 => "Bass Drum 1",
            Self::SideStick => "Side Stick",
            Self::AcousticSnare => "Acoustic Snare",
            Self::HandClap => "Hand Clap",
            Self::ElectricSnare => "Electric Snare",
            Self::LowFloorTom => "Low Floor Tom",
            Self::ClosedHiHat => "Closed Hi-Hat",
            Self::HighFloorTom => "High Floor Tom",
            Self::PedalHiHat => "Pedal Hi-Hat",
            Self::LowTom => "Low Tom",
            Self::OpenHiHat => "Open Hi-Hat",
            Self::LowMidTom => "Low-Mid Tom",
            Self::HiMidTom => "Hi-Mid Tom",
            Self::CrashCymbal1 => "Crash Cymbal 1",
            Self::HighTom => "High Tom",
            Self::RideCymbal1 => "Ride Cymbal 1",
            Self::ChineseCymbal => "Chinese Cymbal",
            Self::RideBell => "Ride Bell",
            Self::Tambourine => "Tambourine",
            Self::SplashCymbal => "Splash Cymbal",
            Self::Cowbell => "Cowbell",
            Self::CrashCymbal2 => "Crash Cymbal 2",
            Self::Vibraslap => "Vibraslap",
            Self::RideCymbal2 => "Ride Cymbal 2",
            Self::HiBongo => "Hi Bongo",
            Self::LowBongo => "Low Bongo",
            Self::MuteHiConga => "Mute Hi Conga",
            Self::OpenHiConga => "Open Hi Conga",
            Self::LowConga => "Low Conga",
            Self::HighTimbale => "High Timbale",
            Self::LowTimbale => "Low Timbale",
            Self::HighAgogo => "High Agogo",
            Self::LowAgogo => "Low Agogo",
            Self::Cabasa => "Cabasa",
            Self::Maracas => "Maracas",
            Self::ShortWhistle => "Short Whistle",
            Self::LongWhistle => "Long Whistle",
            Self::ShortGuiro => "Short Guiro",
            Self::LongGuiro => "Long Guiro",
            Self::Claves => "Claves",
            Self::HiWoodBlock => "Hi Wood Block",
            Self::LowWoodBlock => "Low Wood Block",
            Self::MuteCuica => "Mute Cuica",
            Self::OpenCuica => "Open Cuica",
            Self::MuteTriangle => "Mute Triangle",
            Self::OpenTriangle => "Open Triangle",
        })
    }
}
